edition = "2021"
max_width = 80
comment_width = 80
wrap_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
condense_wildcard_suffixes = true
use_small_heuristics = "Default"
empty_item_single_line = false
force_multiline_blocks = true
error_on_unformatted = true
